name: Cluster Sync Repo
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  DOMAIN: https://tomkidsrepo.cloud
  SUB_REPOS: "package_repo_A1 AppStores"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Clean Packages
        run: |
          rm -f Packages Packages.bz2
          touch Packages

      - name: Download & Merge Packages from Sub-repos
        run: |
          for REPO in $SUB_REPOS; do
            echo "Processing sub-repo: $REPO"
            wget -q -t 3 -O "Packages_$REPO" "$DOMAIN/$REPO/Packages" || true
            
            # Chỉ xử lý nếu file tải về có dung lượng > 0 (bỏ qua 404)
            if [ -s "Packages_$REPO" ]; then
              # Chuyển đổi './file.deb' thành 'TênRepo/file.deb'
              sed -i "s|^Filename: \./|Filename: $REPO/|g" "Packages_$REPO"
              
              cat "Packages_$REPO" >> Packages
              echo "" >> Packages
            fi
            rm -f "Packages_$REPO"
          done

      - name: Compress Packages
        run: bzip2 -fks Packages

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Cluster Repo Updated"
          file_pattern: "Packages Packages.bz2"
