name: Cluster Sync Repo
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-sync]

env:
  DOMAIN: https://tomkidsrepo.cloud
<<<<<<< HEAD
  SUB_REPOS: "package_repo_A1 package_repo_A2 package_repo_A3 package_repo_A4 AppStores -CydiaVn-VietHoa -CydiaVn-Tools -CydiaVn-Themes -CydiaVn-Utilities -CydiaVn-System -CydiaVn-Multimedia -CydiaVn-Hacks -CydiaVn-Games -CydiaVn-Fonts -CydiaVn-Cydget -CydiaVn-Apps"


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Clean Packages
        run: |
          rm -f Packages Packages.bz2
          touch Packages

      - name: Download & Merge Packages from Sub-repos
        run: |
          for REPO in $SUB_REPOS; do
            echo "Processing sub-repo: $REPO"
            wget -q -t 3 -O "Packages_$REPO" "$DOMAIN/$REPO/Packages" || true
            
            # Chỉ xử lý nếu file tải về có dung lượng > 0 (bỏ qua 404)
            if [ -s "Packages_$REPO" ]; then
              # Chuyển đổi './file.deb' thành 'TênRepo/file.deb'
              sed -i "s|^Filename: \./|Filename: $REPO/|g" "Packages_$REPO"
              
              cat "Packages_$REPO" >> Packages
              echo "" >> Packages
            fi
            rm -f "Packages_$REPO"
          done

      - name: Scrub Github URLs from metadata
        run: |
          sed -i -e '/^Filename:/! s|https://github.com/tomkids[a-zA-Z0-9_\.\/-]*|https://tomkidsrepo.cloud|gi' Packages
          sed -i '/^Icon:/d' Packages
          sed -i 's/^Name:/Icon: https:\/\/tomkidsrepo.cloud\/CydiaIcon.png?v=2\nName:/' Packages

      - name: Compress Packages
        run: bzip2 -fks Packages

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Cluster Repo Updated"
          file_pattern: "Packages Packages.bz2"
