name: Auto Update Repo

on:
  schedule:
    - cron: '0 * * * *' # Chạy vào phút thứ 0 của mỗi giờ (60 phút 1 lần)
  workflow_dispatch: # Cho phép bấm nút chạy thủ công (rất hữu ích khi cần cập nhật liền)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout mã nguồn của repo chính
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_TOKEN }} # Sử dụng Token để có quyền đẩy code lên

    - name: Cài đặt công cụ quét gói Debian (dpkg-dev)
      run: sudo apt-get install -y dpkg-dev

    - name: Cấp quyền chạy cho file script
      run: chmod +x ./sync.sh

    - name: Xác thực GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: gh auth status || echo "Xác thực với GH_TOKEN"

    - name: Chạy kịch bản đồng bộ (sync.sh)
      env:
        GH_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: ./sync.sh

    - name: Commit và Đẩy (Push) kết quả mới lên GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # Thêm các file vừa sinh ra hoặc thay đổi
        git add -A
        
        # Chỉ commit nếu có sự thay đổi (tránh lỗi khi không có Tweak nào mới)
        if ! git diff-index --quiet HEAD; then
          git commit -m "Auto-update Cydia Repo packages"
          git push
        else
          echo "Không có thay đổi nào cần cập nhật."
        fi
